[build]
  ignore = "exit 0"

[build.environment]
  NETLIFY_SKIP_SECRETS_SCAN = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

  [functions.runtime]
    node_version = "18"
